import os

from PySide6.QtGui import QPixmap
from PySide6.QtWidgets import QFrame, QPlainTextEdit, QLabel, QVBoxLayout, QHBoxLayout
from PySide6.QtCore import Qt

from kajun_app.BaseKajunApp import BaseKajunApp, Path


ImagesPath = os.path.join(Path, "images")


class KajunInformationPage(QFrame):
    def __init__(self, owner: BaseKajunApp) -> None:
        super(KajunInformationPage, self).__init__()

        # Don't change the function call order
        self.initialiseMemberVariables(owner)
        self.initialiseProperties()
        self.initialiseComponents()


    def initialiseMemberVariables(self, owner: BaseKajunApp) -> None:
        self.owner = owner


    def initialiseProperties(self) -> None:
        self.setFixedHeight(540)
        self.setStyleSheet(str("QFrame{ background-color: #2e2f33; color: white; font: italic; font-size: 12px; }" + 
                                "QPlainTextEdit{ border-color: #26070a; border: 4px }"))


    def initialiseComponents(self) -> None:
        # Page Layout
        self.pageLayout = QVBoxLayout()
        self.pageLayout.setContentsMargins(20, 10, 20, 10)
        self.pageLayout.addSpacing(10)

        # Title Label
        self.titleLabel = QLabel("Would you still have broken it if I hadn't said anything?")
        self.titleLabel.setStyleSheet("color: #fbb03c; font: bold; font-size: 24x;")
        self.titleLabel.setAlignment(Qt.AlignmentFlag.AlignTop)
        self.pageLayout.addWidget(self.titleLabel)

        # Information Frame
        self.infoFrame = QFrame(self)
        self.infoFrameLayout = QHBoxLayout()

        # Information Text
        self.infoText = QPlainTextEdit(self)
        self.infoText.setReadOnly(True)

        self.infoText.setPlainText("Lorem ipsum dolor sit amet, consectetur adipiscing elit.\n" +
                                    "Curabitur quis sagittis nibh, sed vestibulum enim. Donec in nulla sit amet ipsum suscipit egestas eget et neque.\n" +
                                    "Pellentesque imperdiet dui a risus bibendum, a volutpat felis dignissim. Ut in porta quam.\n" +
                                    "Morbi semper porta orci, eu faucibus nisi consectetur eu. Donec sodales eleifend eros, scelerisque semper justo ultrices eu.\n" +
                                    "In vitae diam id lectus lacinia suscipit. Curabitur tincidunt eros sed lacus aliquam, et scelerisque urna venenatis.\n" +
                                    "Proin id iaculis sem, sed lobortis nunc. Cras dictum justo sit amet velit luctus imperdiet. In hac habitasse platea dictumst.\n" +
                                    "Phasellus luctus posuere hendrerit. Sed tristique lacus in ligula imperdiet, id porttitor arcu volutpat.\n" +
                                    "Generated By @tamersum11.")
        
        self.infoFrameLayout.addWidget(self.infoText)
        
        # Information Image
        self.infoImage = QLabel()
        self.infoImage.setPixmap(QPixmap(os.path.join(ImagesPath, "kajun_logo_org.png")))
        self.infoFrameLayout.addWidget(self.infoImage)
        
        self.infoFrame.setLayout(self.infoFrameLayout)
        self.pageLayout.addWidget(self.infoFrame)
        self.setLayout(self.pageLayout)